ManageIQ/amazon_ssa_support

lib/amazon_ssa_support/ssa_bucket.rb, lib/amazon_ssa_support/ssa_common.rb, lib/amazon_ssa_support/ssa_heartbeat.rb, lib/amazon_ssa_support/ssa_queue.rb, lib/amazon_ssa_support/ssa_queue_extractor.rb, spec/ssa_bucket_spec.rb, spec/ssa_heartbeat_spec.rb, spec/ssa_queue_spec.rb
The changes contain: 
1. Enable to initialize SsaQueue without extractor_id;
2. Change region as a must-have parameter;
https://github.com/ManageIQ/amazon_ssa_support/issues/3
https://github.com/ManageIQ/amazon_ssa_support/issues/6
=> Change default parameters request

amazon_ssa_support.gemspec, lib/amazon_ssa_support.rb
This gem needs the manageiq-smartstate gem which was recently split from
the manageiq-gems-pending repo.
@Fryguy please merge.
@roliveri @hsong-rh FYI.
=> Include manageiq-smartstate gem

lib/amazon_ssa_support/ssa_queue.rb
There is a name mismatch in the requeue_request method.  The incorrect naming would
cause the requeue to be done incorrectly.  Fixing.
This addresses Issue https://github.com/ManageIQ/amazon_ssa_support/issues/9.
@hsong-rh @roliveri please review and merge.  Thanks.
=> Fix the tag original_req_id in the requeue_request method.

lib/amazon_ssa_support/ssa_queue.rb
When the Object containing the SSA response, as designated in the
SQS message, is missing from the S3 bucket, we should not simply
issue a warning message.  This should be considered an Exception -
waiting for the Object to show up is not going to do anyone any good.
This was encountered during testing by using an incorrect bucket name,
but if the bucket name were correct we would continue looking for the
object until the request timed out.
@hsong-rh and @roliveri please review and merge.  Thanks much.
=> Missing S3 Object Should Raise an Exception

amazon_ssa_support.gemspec, bin/amazon_ssa_agent
Move the script to a proper bin file, which greatly simplifies actually running the agent, since gem bin paths are on the $PATH
@roliveri Please review.
=> Move extract tool to a proper bin file

lib/amazon_ssa_support/ssa_queue.rb
When the reply object specified by a reply message on the SQS queue
is missing, simply log an error and go on to the next message (if any).
Raising an exception causes the processing to skip the rest of the messages.
This PR is required for the work to support AWS SSA.
@roliveri @hsong-rh please review and merge when appropriate.  Thanks!
=> Don't raise an exception when reply object missing

Gemfile, amazon_ssa_support.gemspec
@hsong-rh @roliveri This will fix the broken ManageIQ master that was caused by #23.  For gems, the gemspec is the source of truth, and the Gemfile is only used in development to enhance it with things like the git based gems.
=> Fix the gemspec to properly point to log_decorator

lib/amazon_ssa_support/miq_ec2_vm/miq_ec2_ebs_instance.rb, lib/amazon_ssa_support/miq_ec2_vm/miq_ec2_ebs_vmbase.rb, lib/amazon_ssa_support/ssa_common.rb
Use more meaningful term smartstate in Amazon environments.
=> Replace ssa with smartstate in queue, bucket, snapshot and volume names

bin/amazon_ssa_agent
Ruby 2.5 doesn't support `YAML.load(content, :safe => true)` anymore, replaced it with `YAML.safe_load(content)`
https://bugzilla.redhat.com/show_bug.cgi?id=1739188
=> Replaced YAML load with safe_load

bin/amazon_ssa_agent, lib/amazon_ssa_support/ssa_queue.rb
This PR removed all `:safe => true` from YAML load and dump methods for ruby 2.5, missing in https://github.com/ManageIQ/amazon_ssa_support/pull/40.
The fix is for the same BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1739188
=> Replace all YAML load/dump for ruby 2.5

.codeclimate.yml
Set rubocop version to 0.69, to fix the code climate errors.
=> Fixed code climate errors

amazon_ssa_support.gemspec, bin/amazon_ssa_agent, lib/amazon_ssa_support/ssa_common.rb, lib/amazon_ssa_support/ssa_heartbeat.rb, lib/amazon_ssa_support/ssa_queue.rb, lib/amazon_ssa_support/ssa_queue_extractor.rb, spec/aws_ssa_commons.rb, spec/miq_ec2_vm/miq_ec2_ebs_instance_spec.rb, spec/miq_ec2_vm/miq_ec2_vm_spec.rb, spec/ssa_bucket_spec.rb, spec/ssa_heartbeat_spec.rb, spec/ssa_queue_extractor_spec.rb, spec/ssa_queue_spec.rb
This is a part of global update `aws-sdk` gem to `v3`
Together with:
- https://github.com/ManageIQ/manageiq-providers-amazon/pull/488
- https://github.com/ManageIQ/manageiq/pull/19411
- https://github.com/ManageIQ/manageiq-gems-pending/pull/449
It should fix https://github.com/ManageIQ/manageiq-providers-amazon/issues/465
=> update aws-sdk gem to v3

Gemfile
Travis is failing because we're using gems-pending 'master' branch.
https://travis-ci.org/ManageIQ/amazon_ssa_support/jobs/601311075
```
Bundler could not find compatible versions for gem "aws-sdk":
In Gemfile:
amazon_ssa_support was resolved to 0.1.0, which depends on
aws-sdk (~> 2.9.7)
manageiq-gems-pending was resolved to 0.1.0, which depends on
aws-sdk (~> 3.0.1)
```
=> [HAMMER] Update git branch for gems-pending

Gemfile
Travis is failing because we're using gems-pending 'master' branch.
https://travis-ci.org/ManageIQ/amazon_ssa_support/jobs/601311091
```
Bundler could not find compatible versions for gem "aws-sdk":
In Gemfile:
amazon_ssa_support was resolved to 0.1.0, which depends on
aws-sdk (~> 2.9.7)
manageiq-gems-pending was resolved to 0.1.0, which depends on
aws-sdk (~> 3.0.1)
```
=> [IVANCHUK] Update git branch ref for gems-pending

Gemfile, amazon_ssa_support.gemspec
Changed to use rubygems.manageiq.org to match manageiq-gems-pending. Copied the changes from https://github.com/ManageIQ/manageiq-gems-pending/pull/456.
Travis failure:
https://travis-ci.org/ManageIQ/amazon_ssa_support/jobs/633595850
```
Bundler could not find compatible versions for gem "handsoap":
In Gemfile:
handsoap (~> 0.2.5)
manageiq-gems-pending was resolved to 0.1.0, which depends on
handsoap (= 0.2.5.5)
Could not find gem 'handsoap (= 0.2.5.5)', which is required by gem
'manageiq-gems-pending', in any of the relevant sources:
https://github.com/ManageIQ/handsoap.git (at v0.2.5-5@b1247a7)
```
@roliveri please review
cc @bdunne
=> List dependency on handsoap from rubygems.manageiq.org

.travis.yml
Lockdown tests to use ruby 2.6.6 per ManageIQ/manageiq#19678
=> Lockdown tests to use ruby 2.6.6 per ManageIQ/manageiq#19678

amazon_ssa_support.gemspec, bin/amazon_ssa_agent, lib/amazon_ssa_support.rb, lib/amazon_ssa_support/instance_metadata.rb, lib/amazon_ssa_support/logging.rb, lib/amazon_ssa_support/miq_ec2_vm/miq_ec2_ebs_vmbase.rb, lib/amazon_ssa_support/ssa_bucket.rb, lib/amazon_ssa_support/ssa_heartbeat.rb, lib/amazon_ssa_support/ssa_queue.rb, lib/amazon_ssa_support/ssa_queue_extractor.rb, spec/miq_ec2_vm/miq_ec2_ebs_instance_spec.rb, spec/spec_helper.rb, spec/ssa_heartbeat_spec.rb, spec/ssa_queue_spec.rb
The log_decorator gem is only used by the one project in the ManageIQ
org with all other projects now archived.  We don't really need the
functionality it provides, and this simplifies the logging experience
@agrare Please review.
=> Drop log_decorator

.github/workflows/ci.yaml
Lock the petrosian release branch to test with ruby 3.0
=> Lock the petrosian release branch to test with ruby 3.0

lib/amazon_ssa_support/miq_ec2_vm/miq_ec2_vmbase.rb
Similar to https://github.com/ManageIQ/manageiq-smartstate/pull/177
Require the gem before requiring libraries inside it
We need to load the zeitwerk loader to retain the autoloading mechanics or the rules around loading constants that don't live in standard locations.
=> Fix name error loading gem-pending files without the zeitwerk loader

lib/amazon_ssa_support/ssa_queue.rb
ActiveSupport Array Conversions uses `ActiveSupport.deprecator` without requiring it: https://github.com/rails/rails/blob/v7.1.4/activesupport/lib/active_support/core_ext/array/conversions.rb#L108
Leading to:
```
An error occurred while loading spec_helper.
Failure/Error: require 'active_support/time_with_zone'
NoMethodError:
undefined method `deprecator' for ActiveSupport:Module
```
=> Require active_support/deprecation and active_support/deprecator
